import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outputsPath = resolve(__dirname, "../cdk-outputs.json");
const envPath = resolve(__dirname, "../../dashboard/.env.local");

const loadOutputs = () => {
  const raw = readFileSync(outputsPath, "utf-8");
  return JSON.parse(raw);
};

const findOutput = (outputs, key) => {
  const matches = [];
  for (const [stackName, stackOutputs] of Object.entries(outputs)) {
    if (
      stackOutputs &&
      Object.prototype.hasOwnProperty.call(stackOutputs, key)
    ) {
      matches.push({ stackName, value: stackOutputs[key] });
    }
  }

  if (matches.length === 0) {
    throw new Error(`Missing CDK output "${key}" in ${outputsPath}`);
  }

  if (matches.length > 1) {
    const stacks = matches.map((match) => match.stackName).join(", ");
    throw new Error(`Multiple outputs found for "${key}": ${stacks}`);
  }

  return matches[0].value;
};

const normalizeApiUrl = (url) =>
  typeof url === "string" && url.endsWith("/") ? url.slice(0, -1) : url;

try {
  const outputs = loadOutputs();
  const apiUrl = normalizeApiUrl(findOutput(outputs, "TemperatureApiUrl"));

  const lines = [
    "# Generated by backend/scripts/generate-env.mjs",
    `VITE_REGION=${findOutput(outputs, "AwsRegion")}`,
    `VITE_COGNITO_USER_POOL_ID=${findOutput(outputs, "CognitoUserPoolId")}`,
    `VITE_COGNITO_USER_POOL_CLIENT_ID=${findOutput(
      outputs,
      "CognitoUserPoolClientId"
    )}`,
    `VITE_BASE_API_URL=${apiUrl}`,
    `VITE_API_URL=${apiUrl}`,
    "",
  ];

  writeFileSync(envPath, lines.join("\n"), "utf-8");
  console.log(`Generated ${envPath}`);
} catch (error) {
  console.error("Failed to generate dashboard/.env.local from CDK outputs.");
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
