#!/usr/bin/env node
import { promises as fs } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();

/** Utility to walk a directory */
async function* walk(dir) {
  for (const d of await fs.readdir(dir, { withFileTypes: true })) {
    const entry = path.join(dir, d.name);
    if (d.isDirectory()) yield* walk(entry);
    else yield entry;
  }
}

function hasTestSibling(file) {
  const dir = path.dirname(file);
  const base = path.basename(file).replace(/\.(ts|tsx)$/i, "");
  const candidates = [
    `${base}.spec.ts`,
    `${base}.spec.tsx`,
    `${base}.test.ts`,
    `${base}.test.tsx`,
  ];
  return candidates;
}

async function fileExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

function isSourceFile(p, root) {
  if (!p.startsWith(path.join(ROOT, root, "src"))) return false;
  if (!/\.(ts|tsx)$/.test(p)) return false;
  if (p.endsWith(".d.ts")) return false;
  if (/\.(spec|test)\.(ts|tsx)$/.test(p)) return false;
  return true;
}

async function ensureTestForFile(srcFile, kind) {
  const dir = path.dirname(srcFile);
  const base = path.basename(srcFile).replace(/\.(ts|tsx)$/i, "");
  const exts = srcFile.endsWith(".tsx") ? [".spec.tsx"] : [".spec.ts"];
  const candidates = exts.map((ext) => path.join(dir, `${base}${ext}`));
  for (const cand of candidates) {
    if (await fileExists(cand)) return null; // Already has a test
  }
  const out = candidates[0];
  const rel = path
    .relative(path.join(ROOT, kind), srcFile)
    .replace(/^src\//, "");
  let content = "";
  if (kind === "backend") {
    content = `// Auto-generated by Test Writer\nimport { describe, it, expect } from '@jest/globals'\n\ndescribe('${rel}', () => {\n  it('smoke', () => {\n    expect(1 + 1).toBe(2)\n  })\n})\n`;
  } else {
    // dashboard (vitest)
    content = `// Auto-generated by Test Writer\nimport { describe, it, expect } from 'vitest'\n\ndescribe('${rel}', () => {\n  it('smoke', () => {\n    expect(1 + 1).toBe(2)\n  })\n})\n`;
  }
  await fs.writeFile(out, content, "utf8");
  return out;
}

async function main() {
  const results = [];
  for (const kind of ["backend", "dashboard"]) {
    const root = path.join(ROOT, kind);
    try {
      for await (const f of walk(path.join(root, "src"))) {
        if (isSourceFile(f, kind)) {
          const created = await ensureTestForFile(f, kind);
          if (created) results.push(created);
        }
      }
    } catch (e) {
      // skip missing workspace
    }
  }
  if (results.length) {
    console.log(`Created ${results.length} test stub(s):`);
    results.forEach((r) => console.log(" -", path.relative(ROOT, r)));
  } else {
    console.log(
      "No new tests created. All files have tests or workspaces missing."
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
