#!/usr/bin/env python3
"""Generate missing unit test stubs (optionally via Gemini).

This script scans selected project folders for TypeScript source files and
creates colocated `*.spec.ts` / `*.spec.tsx` files when no test sibling exists.

Modes (env `TEST_WRITER_MODE`):
  - stub: always generate minimal smoke tests
  - auto: try Gemini, fall back to stub if not configured or fails
  - llm: require Gemini; fail if not configured or call fails

Gemini (Google AI Studio) configuration:
  - GEMINI_API_KEY: required for `auto`/`llm`
  - GEMINI_MODEL: optional (default: gemini-pro-latest)

Usage:
  python agents/tasks/generate_tests.py
  TEST_WRITER_MODE=auto GEMINI_API_KEY=... python agents/tasks/generate_tests.py
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional


def _env(name: str, fallback: str = "") -> str:
    return (os.getenv(name, fallback) or "").strip()


def _strip_code_fences(text: str) -> str:
    s = (text or "").strip()
    if s.startswith("```") and s.endswith("```"):
        # Drop first fence line and last fence line
        lines = s.splitlines()
        if len(lines) >= 3:
            return "\n".join(lines[1:-1]).strip()
    return s


@dataclass(frozen=True)
class KindConfig:
    name: str
    root_dir: Path
    src_dir: Path
    runner: str
    notes: str


def _iter_files(folder: Path) -> Iterable[Path]:
    if not folder.exists():
        return
    for p in folder.rglob("*"):
        if p.is_file():
            yield p


def _is_source_ts_file(file_path: Path, src_dir: Path) -> bool:
    try:
        file_path.relative_to(src_dir)
    except ValueError:
        return False

    if file_path.suffix.lower() not in {".ts", ".tsx"}:
        return False
    if file_path.name.endswith(".d.ts"):
        return False
    lower = file_path.name.lower()
    if lower.endswith(".spec.ts") or lower.endswith(".spec.tsx"):
        return False
    if lower.endswith(".test.ts") or lower.endswith(".test.tsx"):
        return False
    return True


def _test_candidates_for_source(src_file: Path) -> list[Path]:
    base = src_file.name
    if base.lower().endswith(".tsx"):
        stem = base[:-4]
        exts = [".spec.tsx", ".test.tsx"]
    else:
        stem = base[:-3]
        exts = [".spec.ts", ".test.ts"]
    return [src_file.with_name(stem + ext) for ext in exts]


def _existing_test_sibling(src_file: Path) -> Optional[Path]:
    for cand in _test_candidates_for_source(src_file):
        if cand.exists():
            return cand
    return None


def _default_stub_content(rel_module: str, runner: str, import_path: str) -> str:
    """Return a tiny, stable smoke test.

    We prefer importing the module to ensure TypeScript pathing works.
    We intentionally avoid assuming default exports or React component shapes.
    """

    if runner == "jest":
        return (
            "// Auto-generated by Test Writer\n"
            "import { describe, it, expect } from '@jest/globals'\n"
            f"import * as mod from '{import_path}'\n\n"
            f"describe('{rel_module}', () => {{\n"
            "  it('smoke: module imports', () => {\n"
            "    expect(mod).toBeDefined()\n"
            "  })\n"
            "})\n"
        )

    # vitest globals style
    return (
        "// Auto-generated by Test Writer\n"
        f"import * as mod from '{import_path}'\n\n"
        f"describe('{rel_module}', () => {{\n"
        "  it('smoke: module imports', () => {\n"
        "    expect(mod).toBeDefined()\n"
        "  })\n"
        "})\n"
    )


def _gemini_generate_test(
    *,
    api_key: str,
    model_name: str,
    system: str,
    user: str,
    temperature: float,
) -> str:
    try:
        import importlib

        genai = importlib.import_module("google.generativeai")
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError("Missing dependency 'google-generativeai'. Install agents/requirements.txt.") from exc

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel(model_name=model_name, system_instruction=system)
    resp = model.generate_content(
        user,
        generation_config={"temperature": temperature},
    )
    text = getattr(resp, "text", None)
    if not text:
        raise RuntimeError("Gemini returned empty content")
    return text


def _ensure_test_for_file(src_file: Path, kind: KindConfig, mode: str) -> Optional[Path]:
    if _existing_test_sibling(src_file):
        return None

    # Determine output file name (prefer *.spec.*)
    candidates = _test_candidates_for_source(src_file)
    out_file = next((p for p in candidates if p.name.endswith(".spec.ts") or p.name.endswith(".spec.tsx")), candidates[0])

    # Compute a stable "relative module" label for describe()
    rel = src_file.relative_to(kind.root_dir).as_posix()
    rel_module = rel
    if rel_module.startswith("src/"):
        rel_module = rel_module[len("src/") :]

    content = ""
    import_path = f"./{src_file.stem}"

    try_llm = mode in {"auto", "llm"}
    if try_llm:
        api_key = _env("GEMINI_API_KEY")
        model_name = _env("GEMINI_MODEL", "gemini-pro-latest")
        if not api_key:
            if mode == "llm":
                raise RuntimeError("Gemini not configured (missing GEMINI_API_KEY).")
        else:
            src_text = src_file.read_text(encoding="utf-8")
            system = (
                "You are a senior engineer writing unit tests. "
                "Output ONLY the test file content. "
                "Do not include markdown fences, explanations, or extra files."
            )

            kind_hint = f"Project: {kind.name}\nTest runner: {kind.runner}\nNotes: {kind.notes}\n"
            user = "\n".join(
                [
                    kind_hint,
                    f"Target relative module: {rel_module}",
                    "Constraints:",
                    "- Use existing dependencies only (no new packages).",
                    "- Prefer small, stable tests that won't be flaky.",
                    "- If the file is a React component and the project has @testing-library/react, write a smoke render test.",
                    "- If external services are involved, mock them minimally.",
                    "- If you cannot confidently test behavior, produce a minimal smoke test that imports the module and asserts something trivial.",
                    "",
                    "Source file content:",
                    "-----",
                    src_text,
                    "-----",
                ]
            )

            try:
                llm_out = _gemini_generate_test(
                    api_key=api_key,
                    model_name=model_name,
                    system=system,
                    user=user,
                    temperature=0.1,
                )
                stripped = _strip_code_fences(llm_out)
                if stripped and len(stripped) > 20:
                    content = "// Auto-generated by Test Writer (Gemini)\n" + stripped.strip() + "\n"
            except Exception:
                if mode == "llm":
                    raise
                # auto -> fall back to stub

    if not content:
        content = _default_stub_content(rel_module, kind.runner, import_path)

    out_file.write_text(content, encoding="utf-8")
    return out_file


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate missing test stubs (Gemini optional).")
    parser.add_argument(
        "--kinds",
        nargs="*",
        default=["dashboard", "homepage"],
        help="Which projects to scan: dashboard homepage backend",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]

    mode = _env("TEST_WRITER_MODE", "stub").lower()
    if mode not in {"stub", "auto", "llm"}:
        print(f"Invalid TEST_WRITER_MODE: {mode} (use stub|auto|llm)", file=sys.stderr)
        return 2

    kind_map: dict[str, KindConfig] = {
        "dashboard": KindConfig(
            name="dashboard",
            root_dir=repo_root / "dashboard",
            src_dir=repo_root / "dashboard" / "src",
            runner="vitest",
            notes="Use Vitest globals style. For React components, prefer @testing-library/react if available.",
        ),
        "homepage": KindConfig(
            name="homepage",
            root_dir=repo_root / "homepage",
            src_dir=repo_root / "homepage" / "src",
            runner="vitest",
            notes="This project may not have a test runner configured; keep tests minimal and dependency-free.",
        ),
        "backend": KindConfig(
            name="backend",
            root_dir=repo_root / "backend",
            src_dir=repo_root / "backend" / "src",
            runner="jest",
            notes="Use Jest. Keep tests minimal and deterministic.",
        ),
    }

    selected: list[KindConfig] = []
    for k in args.kinds:
        if k not in kind_map:
            print(f"Unknown kind: {k} (allowed: dashboard homepage backend)", file=sys.stderr)
            return 2
        selected.append(kind_map[k])

    created: list[Path] = []
    for kind in selected:
        if not kind.src_dir.exists():
            continue
        for file_path in _iter_files(kind.src_dir):
            if not _is_source_ts_file(file_path, kind.src_dir):
                continue
            out = _ensure_test_for_file(file_path, kind, mode)
            if out:
                created.append(out)

    if created:
        print(f"Created {len(created)} test stub(s):")
        for p in created:
            print(" -", p.relative_to(repo_root).as_posix())
    else:
        print("No new tests created. All files have tests or selected workspaces missing.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
