#!/usr/bin/env python3
"""
Auto-update PR description with a structured template.

Inputs (env):
- GITHUB_TOKEN (required)
- REPO (owner/name) (required)
- PR_NUMBER (required)
"""
from __future__ import annotations
import os, sys, textwrap, requests

API = "https://api.github.com"

def env(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        print(f"Missing env: {name}", file=sys.stderr)
        sys.exit(1)
    return v

TOKEN = env("GITHUB_TOKEN")
REPO = env("REPO")
PR_NUMBER = env("PR_NUMBER")

session = requests.Session()
session.headers.update({
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
})

def gh(method: str, path: str, *, params=None, body=None):
    url = f"{API}{path}"
    r = session.request(method.upper(), url, params=params, json=body)
    if r.status_code >= 400:
        raise RuntimeError(f"GitHub API {method} {path} failed: {r.status_code} {r.text}")
    if r.text.strip():
        return r.json()
    return {}

def list_changed_files(repo: str, pr_number: str) -> list[dict]:
    files = []
    page = 1
    while True:
        resp = gh("GET", f"/repos/{repo}/pulls/{pr_number}/files", params={"per_page": 100, "page": page})
        if not resp:
            break
        if isinstance(resp, list):
            files.extend(resp)
            if len(resp) < 100:
                break
        else:
            break
        page += 1
    return files

def summarize_components(paths: list[str]) -> list[str]:
    components = set()
    for p in paths:
        top = p.split("/", 1)[0]
        if top in {"backend", "dashboard", "board", "agents", ".github"}:
            components.add(top)
        else:
            components.add(top or p)
    return sorted(components)

def extract_user_content(body: str | None) -> str:
    """Extracts user-written content from a PR body, ignoring the autogenerated block."""
    if not body:
        return ""
    
    marker = "<!-- autogenerated:pr-description -->"
    start = body.find(marker)
    end = body.rfind(marker)

    if start != -1 and end != -1 and end > start:
        # User content is everything BEFORE the autogenerated block.
        return body[:start].rstrip()
    
    # If no markers, the whole body is user content
    return body

def build_body(pr: dict, files: list[dict], user_content: str) -> str:
    changed = [f.get("filename", "") for f in files]
    additions = sum(f.get("additions", 0) for f in files)
    deletions = sum(f.get("deletions", 0) for f in files)
    components = summarize_components(changed)

    checklist = """
- [ ] Lint passes (backend/dashboard)
- [ ] Unit tests pass (Jest/Vitest)
- [ ] Coverage uploaded (lcov)
- [ ] Security scans clean (Gitleaks, Semgrep)
- [ ] Sonar analysis succeeded
""".strip()

    files_preview = "\n".join(f"- {p}" for p in changed[:20])
    if len(changed) > 20:
        files_preview += f"\n- … and {len(changed) - 20} more"

    autogenerated_marker = "<!-- autogenerated:pr-description -->"
    
    # Combine user content with the new autogenerated block
    new_body_parts = []
    if user_content:
        new_body_parts.append(user_content)

    auto_block = f"""
{autogenerated_marker}
### Summary
- Title: {pr.get('title')}
- Author: @{pr.get('user', {}).get('login')}
- Components: {', '.join(components) if components else 'n/a'}
- Changes: +{additions} / -{deletions} across {len(changed)} files

### Files changed (preview)
{files_preview or 'n/a'}

### Checklist
{checklist}

### Notes
- This description was auto-generated and will update on new commits.
{autogenerated_marker}
""".strip()
    
    new_body_parts.append(textwrap.dedent(auto_block))
    
    return "\n\n".join(new_body_parts)

def main():
    pr = gh("GET", f"/repos/{REPO}/pulls/{PR_NUMBER}")
    files = list_changed_files(REPO, PR_NUMBER)
    
    existing_body = pr.get("body")
    user_content = extract_user_content(existing_body)
    
    # The 'What changed' section is now the user_content, which is handled separately.
    # We pass the user_content to build_body to construct the full new description.
    new_body = build_body(pr, files, user_content)
    
    if new_body != existing_body:
        gh("PATCH", f"/repos/{REPO}/pulls/{PR_NUMBER}", body={"body": new_body})
        print("PR description updated.")
    else:
        print("PR description already up to date.")

if __name__ == "__main__":
    main()
