#!/usr/bin/env python3
"""
Auto-update PR description with a structured template.

Inputs (env):
- GITHUB_TOKEN (required)
- REPO (owner/name) (required)
- PR_NUMBER (required)
"""
from __future__ import annotations
import os, sys, textwrap, requests

API = "https://api.github.com"

def env(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        print(f"Missing env: {name}", file=sys.stderr)
        sys.exit(1)
    return v

TOKEN = env("GITHUB_TOKEN")
REPO = env("REPO")
PR_NUMBER = env("PR_NUMBER")

session = requests.Session()
session.headers.update({
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
})

def gh(method: str, path: str, *, params=None, body=None):
    url = f"{API}{path}"
    r = session.request(method.upper(), url, params=params, json=body)
    if r.status_code >= 400:
        raise RuntimeError(f"GitHub API {method} {path} failed: {r.status_code} {r.text}")
    if r.text.strip():
        return r.json()
    return {}

def list_changed_files(repo: str, pr_number: str) -> list[dict]:
    files = []
    page = 1
    while True:
        resp = gh("GET", f"/repos/{repo}/pulls/{pr_number}/files", params={"per_page": 100, "page": page})
        if not resp:
            break
        if isinstance(resp, list):
            files.extend(resp)
            if len(resp) < 100:
                break
        else:
            break
        page += 1
    return files

def summarize_components(paths: list[str]) -> list[str]:
    components = set()
    for p in paths:
        top = p.split("/", 1)[0]
        if top in {"backend", "dashboard", "board", "agents", ".github"}:
            components.add(top)
        else:
            components.add(top or p)
    return sorted(components)

def build_body(pr: dict, files: list[dict]) -> str:
    changed = [f.get("filename", "") for f in files]
    additions = sum(f.get("additions", 0) for f in files)
    deletions = sum(f.get("deletions", 0) for f in files)
    components = summarize_components(changed)

    checklist = """
- [ ] Lint passes (backend/dashboard)
- [ ] Unit tests pass (Jest/Vitest)
- [ ] Coverage uploaded (lcov)
- [ ] Security scans clean (Gitleaks, Semgrep)
- [ ] Sonar analysis succeeded
""".strip()

    files_preview = "\n".join(f"- {p}" for p in changed[:20])
    if len(changed) > 20:
        files_preview += f"\n- … and {len(changed) - 20} more"

    autogenerated_marker = "<!-- autogenerated:pr-description -->"
    body = f"""
{autogenerated_marker}
### Summary
- Title: {pr.get('title')}
- Author: @{pr.get('user', {}).get('login')}
- Components: {', '.join(components) if components else 'n/a'}
- Changes: +{additions} / -{deletions} across {len(changed)} files

### What changed
{pr.get('body') or '(no description provided)'}

### Files changed (preview)
{files_preview or 'n/a'}

### Checklist
{checklist}

### Notes
- This description was auto-generated and will update on new commits.
{autogenerated_marker}
""".strip()
    return textwrap.dedent(body)

def merge_with_existing(existing: str | None, new: str) -> str:
    if not existing:
        return new
    start = existing.find("<!-- autogenerated:pr-description -->")
    end = existing.rfind("<!-- autogenerated:pr-description -->")
    if start != -1 and end != -1 and end > start:
        # Replace between markers (inclusive) with new
        before = existing[:start].rstrip()
        after = existing[end + len("<!-- autogenerated:pr-description -->"):].lstrip()
        merged = "\n\n".join([p for p in [before, new, after] if p])
        return merged
    # Append if no markers
    return (existing + "\n\n" + new).strip()

def main():
    pr = gh("GET", f"/repos/{REPO}/pulls/{PR_NUMBER}")
    files = list_changed_files(REPO, PR_NUMBER)
    new_block = build_body(pr, files)
    merged = merge_with_existing(pr.get("body"), new_block)
    if merged != pr.get("body"):
        gh("PATCH", f"/repos/{REPO}/pulls/{PR_NUMBER}", body={"body": merged})
        print("PR description updated.")
    else:
        print("PR description already up to date.")

if __name__ == "__main__":
    main()
